language: go

# Don't email me the results of the test runs.
notifications:
  email: false

# script always run to completion (set +e). All of these code checks are must haves
# in a modern Go project.
script:
  - go test ./